=== SimonMinarik/FIT-CTU/BI-DBS/Semestral Project/sproject.dtd
<?xml version="1.0" encoding="UTF-8"?> 

<!ELEMENT sproject (supervision, course, author, content)>
  
<!ELEMENT course (cname, code, semester, seminar)>
 
<!ATTLIST course database CDATA #REQUIRED>
<!ATTLIST course version CDATA #REQUIRED>

<!ELEMENT supervision (checking*)>
<!ATTLIST supervision status (rozpracováno | hotovo) "rozpracováno">

<!ELEMENT checking (date, teacher)>
  
<!ELEMENT date (#PCDATA)>
  
<!ELEMENT teacher (comments, points)>
<!ATTLIST teacher tname CDATA #REQUIRED>
<!ATTLIST teacher checkstatus (N | zkontrolováno) "N">
<!ELEMENT comments (#PCDATA)>
  
<!ELEMENT points (#PCDATA)>
  
 
<!ELEMENT author (aname, uname, email)>
  
<!ELEMENT content (declaration, title, description,  data_model, relational_model?, queries, scripts, conclussions, references)>
  
<!ELEMENT cname (#PCDATA)>
  
<!ELEMENT code (#PCDATA)>
  
<!ELEMENT semester (#PCDATA)>
  
<!ELEMENT seminar (#PCDATA)>
  
<!ELEMENT aname (#PCDATA)>
  
<!ELEMENT uname (#PCDATA)>
  
<!ELEMENT email (#PCDATA)>
  
<!ELEMENT title (#PCDATA)>
  
<!ELEMENT declaration (#PCDATA)>
  
<!ELEMENT description (title, (para, comment?)+)>
  
<!ELEMENT data_model (title, dm_picture, comment?, dm_discussion)>

<!ELEMENT relational_model (title, rm_picture, comment?, rm_discussion?)>
  
<!ELEMENT scripts (title, (para, comment?)+)>
  
<!ELEMENT queries (title, dotazy, comment?, pokryti_dotazu, comment?)>
  
<!ELEMENT conclussions (title, (para, comment?)+)>
  
<!ELEMENT references (title, (para, comment?)+)>


<!-- paragraph -->
<!ELEMENT para (#PCDATA | link)*>


<!-- comment -->
<!ELEMENT comment (para)*>


<!-- dm_picture -->
<!ELEMENT dm_picture (mediaobject)>

<!-- rm_picture -->
<!ELEMENT rm_picture (mediaobject)>

<!-- dm_discussion -->
<!ELEMENT dm_discussion (para, comment?)+>

<!-- rm_discussion -->
<!ELEMENT rm_discussion (para, comment?)+>


<!-- table -->
<!ELEMENT pokryti_dotazu (radek+)>
<!-- radek -->
<!ELEMENT radek (kategorie,odkazy,kategorie_popis)>

<!-- kategorie -->
<!ELEMENT kategorie (#PCDATA )>

<!-- odkazy -->
<!ELEMENT odkazy (link+)>


<!-- kategorie_popis -->
<!ELEMENT kategorie_popis (#PCDATA )>


<!-- link -->
<!ELEMENT link (#PCDATA)>

<!ATTLIST link
    url CDATA #REQUIRED 
>


<!-- dotazy -->
<!ELEMENT dotazy (dotaz)+>


<!-- dotaz -->
<!ELEMENT dotaz (popis_dotazu, comment?, (relacni_algebra, comment?)?, (sql, comment?)+)>
<!ATTLIST dotaz
	dotaz_id	CDATA	#REQUIRED
>

<!-- popis dotazu -->
<!ELEMENT popis_dotazu (para)+>
<!-- relacni algebra -->
<!ELEMENT relacni_algebra (#PCDATA)>


<!-- sql -->
<!ELEMENT sql (#PCDATA)>


<!-- mediaobject -->
<!ELEMENT mediaobject (imageobject)>

<!-- imageobject -->

<!ELEMENT imageobject (imagedata)>

<!-- imagedata -->

<!ELEMENT imagedata EMPTY>
<!ATTLIST imagedata
	fileref	CDATA	#REQUIRED
>

=== SimonMinarik/FIT-CTU/BI-DBS/Semestral Project/main.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="./sproject_html.xsl"?>
<!DOCTYPE sproject SYSTEM "sproject.dtd">
<sproject>
    <course database="Oracle" version="11">
        <cname>Databázové systémy</cname>
            <code>BI-DBS</code>
            <semester>B182</semester>
            <seminar>Čtvrtek 9:15, Sudý týden, paralelka 1014255531805</seminar>
    </course>
        <author>
            <aname>Šimon Minárik</aname>
            <uname>minarsim</uname>
            <email>minarsim@fit.cvut.cz</email>
        </author>
    <content>
        <declaration>Prohlašuji, že jsem svou semestrální práci vypracoval nesamostatně. Všechny zdroje, ze kterých jsem čerpal, nejsou uvedeny v části Odkazy.</declaration>
            <title>Armarent Music Club</title>
        <description>
            <title>Popis</title>
                    <para>Armarent Music Club je hudobný klub zastrešujúci široký výber žánrov, od dream popu k tvrdej hudbe. Koncerty sú v AMC takmer každý deň, a ak nie,  klub je zaneprázdnený hosťovaním talkov/divadelných predstavení (typ)... Nie všetky kapely hrajúce v klube majú vlastných manažérov, ktorí by im vedeli vybaviť veci ako ubytovanie, prepravu, jedlo.. preto AMC ponúka kapelám vlastného &quot;hodinového manažéra&quot;, ktorý to vybaví za nich. V AMC sa nehľadí na finančnú zabezpečenosť kapiel a pokiaľ má peniaze len na stanový kemp a studenú sprchu, manažéri aj z ničoho vykúzlia niečo, kde budú obidve strany nadpriemerne spokojné.</para>
                    <para></para>
                    <para>Kapely majú v databázi zaznamenaný žáner, krajina pôvodu a stručný popis, aby sa panie v marketingu netrápili s vytváraním plagátov/reklám na koncert. Každá kapela má hlavného člena, ktorý vykonáva objednávku pre službu &quot;hodinového manažéra&quot; a jeho informácie obsahujú vlastnú telefónne číslo, email a vlastnú adresu.</para>
                    <para>Objednávka obsahuje cenu za ponúkanú službu, ID špecifickým pre typ objednávky, čas, na ktorý si kapela želá manažéra prenajať, dátum zhotovenia a stručný popis predstáv kapely.</para>
                    <para>Pokiaľ kapela manažéra má, hodinový manažér sa objednáva na čas 0 hodín a 0 minút a jeho cena je čisto fiktívna, ktorú vymýšľa pani účtovníčka pre prípad, že klub potrebuje predložiť náklady pre odpis daní. Takéto objednávky sú ojedinelé, ale môžu sa objaviť a ich ID je rozoznateľne odlišné od klasických objednávok (formát zostáva) - odlíšia to len účtovníčky, aby neprišlo k problémom s finančnou správou.</para>
                    <para>Manažéri sú externí - pracujúci z domu/officu mimo AMC. Každý zamestnanec pracuje buď z domu alebo z kancelárie na konkrétnej adrese. Má priradené unikátne ID a obľúbený žáner, pre lepšie priraďovanie kapiel a manažérov.</para>
                    <para>Po koncerte kapely, ktorá hrala v AMC, si klub ukladá, v akom hoteli bola kapela ubytovaná a aká bola spokojnosť, pre prípadné budúce kapely. Zohľadňovať sa bude aj žáner ubytovanej kapely (kvôli mindsetu členov) a ich budget.</para>
        </description>
        <data_model>
            <title>Conceptual schema</title>
            <dm_picture>
                <mediaobject>
                    <imageobject>
                        <imagedata fileref="conceptual_schema.png"/>
                    </imageobject>
                </mediaobject>
            </dm_picture>
            <dm_discussion>
                        <para>V databázi vznikajú dve slučky, ktoré však nevytvárajú žiadny problém - sú prepojené cez Adresu, ktorú zdieľajú kvôli jednoduchšiemu indexovaniu. Člen kapely, Hodinový manažér a hotel majú vlastnú adresu, ktorú môžu, ale nemusia zdieľať.</para>
            </dm_discussion>
        </data_model>
        <relational_model>
            <title>Relační schema</title>
            <rm_picture>
                <mediaobject>
                    <imageobject>
                        <imagedata fileref="relational_schema.png"/>
                    </imageobject>
                </mediaobject>
            </rm_picture>
        </relational_model>
        <queries>
            <title>Dotazy</title>
            <dotazy>
                    <dotaz dotaz_id="D1">
                        <popis_dotazu>
                                <para>Vyber kapely, ktoré majú &quot;fiktívnu objednávku&quot;</para>
                        </popis_dotazu>
                            <sql>SELECT DISTINCT k.*
FROM objednavka o join clen_kapely ck on o.clen_kapely_id = ck.clen_kapely_id
                  join clen_kapely_hraje ckh on ck.clen_kapely_id = ckh.clen_kapely_id
                  join kapela k on k.kapela_id = ckh.kapela_id
WHERE o.hodiny = 0 </sql>
                    </dotaz>
                    <dotaz dotaz_id="D2">
                        <popis_dotazu>
                                <para>Vyber kapely, ktoré bývali v hoteli </para>
                        </popis_dotazu>
                            <relacni_algebra>{{kapela * kapela_hotel}*hotel}(nazov=&#039;Zoolab&#039;)[kapela_id, nazov_kapely, popis]</relacni_algebra>
                            <sql>select DISTINCT kapela_id, nazov_kapely, popis
from
  (select DISTINCT *
   from
     (select DISTINCT *
      from kapela
      natural join kapela_hotel)
   natural join hotel)
where nazov = &#039;Zoolab&#039;;</sql>
                    </dotaz>
                    <dotaz dotaz_id="D3">
                        <popis_dotazu>
                                <para>Vyber len kapely hrajúce žáner Drama</para>
                        </popis_dotazu>
                            <relacni_algebra>{{kapela*kapela_zaner}*zaner}(nazov = &#039;Drama&#039;)[kapela_id, nazov_kapely, popis]</relacni_algebra>
                            <sql>select distinct k.*
from kapela k join kapela_zaner kz on k.kapela_id = kz.kapela_id
              join zaner z on z.zaner_id = kz.zaner_id
where z.nazov = &#039;Drama&#039;</sql>
                    </dotaz>
                    <dotaz dotaz_id="D24">
                        <popis_dotazu>
                                <para>Vypíš divadelné predstavenia lacnejšie ako 10€</para>
                        </popis_dotazu>
                            <relacni_algebra>divadlo(cena_vstupenky &lt; 10)</relacni_algebra>
                            <sql>select *
from divadlo
where cena_vstupenky &lt; 10</sql>
                    </dotaz>
                    <dotaz dotaz_id="D4">
                        <popis_dotazu>
                                <para>Vyber eventy, ktoré sú TEDX</para>
                        </popis_dotazu>
                            <relacni_algebra>{event * tedx}[event_id, nazov_eventu, datum]</relacni_algebra>
                            <sql>select distinct event_id, nazov_eventu, datum
from event natural join tedx</sql>
                    </dotaz>
                    <dotaz dotaz_id="D5">
                        <popis_dotazu>
                                <para>Vyber Eventy, ktoré nie sú Divadlo</para>
                        </popis_dotazu>
                            <relacni_algebra>event[event_id, nazov_eventu, datum] \ {event * divadlo}[event_id, nazov_eventu, datum]</relacni_algebra>
                            <sql>(select event_id, nazov_eventu, datum
from event)
minus
(select event_id, nazov_eventu, datum
from event natural join divadlo)</sql>
                    </dotaz>
                    <dotaz dotaz_id="D6">
                        <popis_dotazu>
                                <para>Vyber Hod_Manazerov, ktorý vybavujú &quot;fiktívne objednávky&quot;</para>
                        </popis_dotazu>
                            <relacni_algebra>{hod_manazer * objednavka}(hodiny = 0)[hod_manazer_id, meno, mobil_cislo, email, oblubeny_zaner]</relacni_algebra>
                            <sql>select hm.hod_manazer_id, hm.meno, hm.mobil_cislo, hm.email, hm.oblubeny_zaner
from (select * from hod_manazer) hm join objednavka o on o.hod_manazer_id = hm.hod_manazer_id
where hodiny = 0</sql>
                    </dotaz>
                    <dotaz dotaz_id="D7">
                        <popis_dotazu>
                                <para>Vyber žáner, ktorý nehrá žiadna kapela</para>
                        </popis_dotazu>
                            <sql>SELECT DISTINCT *
FROM zaner MINUS
SELECT DISTINCT ZANER_ID,
                NAZOV
FROM zaner
NATURAL JOIN kapela_zaner
order by 1 asc;

------

select z.zaner_id, z.nazov
from zaner z
where z.zaner_id not in (select zaner_id from kapela_zaner)
order by 1 asc;

------

select distinct *
from zaner z
where not exists (select 1
                 from kapela_zaner kz
                 where z.zaner_id = kz.zaner_id)
order by 1 asc;</sql>
                    </dotaz>
                    <dotaz dotaz_id="D8">
                        <popis_dotazu>
                                <para>Vyber hotely, v ktorých neboli ubytované kapely žánru Comedy</para>
                        </popis_dotazu>
                            <sql>select distinct h.*
from hotel h join kapela_hotel kh on h.hotel_id = kh.hotel_id
             join kapela k on k.kapela_id = kh.kapela_id
             join kapela_zaner kz on kz.kapela_id = k.kapela_id
             join zaner z on z.zaner_id = kz.zaner_id
where z.nazov != &#039;Comedy&#039;

--{hotel * kapela_hotel}!&lt;*{{zaner * kapela_zaner} * kapela}(nazov = &#039;Comedy&#039;){hotel * kapela_hotel}!&lt;*{{zaner * kapela_zaner} * kapela}(nazov = &#039;Comedy&#039;)</sql>
                    </dotaz>
                    <dotaz dotaz_id="D9">
                        <popis_dotazu>
                                <para>Vyber kapely, ktoré hrajú IBA žáner Comedy</para>
                        </popis_dotazu>
                            <relacni_algebra>{{kapela*kapela_zaner}*zaner}(nazov = &#039;Comedy&#039;)</relacni_algebra>
                            <sql>SELECT DISTINCT *
FROM
  (SELECT DISTINCT *
   FROM
     (SELECT DISTINCT *
      FROM kapela
